"""One targeted synthetic repro of the static LME ordinal discrepancy, not a suite rerun.

Unchanged real Python functions ingest generated bytes, fit, score and build envelope.
Only source/mapping checks are replaced with exact checks for our generated fixture,
as in the candidate integration test. No accepted stamp or authorization is created.
"""
import copy
import hashlib
import json
import os
from pathlib import Path
import sys
from unittest import mock

AUDIT = Path(__file__).resolve().parent
NS = AUDIT / 'v52/membership_g3_remediation_2026_09_11'
for name in ('OMP_NUM_THREADS', 'OPENBLAS_NUM_THREADS', 'MKL_NUM_THREADS', 'NUMEXPR_NUM_THREADS',
             'OMP_THREAD_LIMIT', 'BLIS_NUM_THREADS', 'VECLIB_MAXIMUM_THREADS'):
    os.environ[name] = '1'
sys.path.insert(0, str(NS))
import corpus_ingest_g3 as ingest
import integration_g3 as bridge
import pipeline_g3 as pipeline

ROOT = AUDIT / 'targeted_scratch'
ROOT.mkdir(exist_ok=False)
events = {'synthetic_data': 0, 'denied': 0}
def guard(event, args):
    if event in ('socket.connect', 'socket.getaddrinfo'):
        events['denied'] += 1
        raise RuntimeError('network forbidden')
    if event not in ('open', 'os.scandir', 'os.listdir') or not args or not isinstance(args[0], (str, bytes, os.PathLike)):
        return
    p = Path(os.fsdecode(args[0])).resolve()
    if p.suffix.lower() not in ('.json', '.jsonl', '.csv', '.gz', '.parquet'):
        return
    if AUDIT in p.parents:
        events['synthetic_data'] += 1
        return
    events['denied'] += 1
    raise RuntimeError('external data forbidden')
sys.addaudithook(guard)

ids = ['q_z', 'q_a']
items = []
for offset, qid in enumerate(ids):
    turns = [{'role': 'user', 'has_answer': True,
              'content': f'synthetic archive token{j} topic{j % (13 + offset)} item{j * (17 + offset)} detail{j % 7}'}
             for j in range(110)]
    items.append(dict(question_id=qid, question='synthetic topic3 item34 query',
                      haystack_session_ids=['fixture_session'], haystack_dates=['synthetic date'],
                      haystack_sessions=[turns]))
raw = json.dumps(items).encode()
path = ROOT / 'synthetic_fixture.json'
path.write_bytes(raw)
digest = hashlib.sha256(raw).hexdigest()
mapping = dict(provenance=bridge.SYNTHETIC, source_id='synthetic_fixture', source_sha256=digest,
               benchmark='LongMemEval', n_questions=2, expected_cluster_ids=['synthetic_component'],
               expected_question_to_cluster=dict.fromkeys(ids, 'synthetic_component'))
identity = dict(source_file=path.name, source_sha256=digest, source_bytes=len(raw))
def fixture_bytes(p, benchmark, *, enabled=None):
    assert Path(p) == path and benchmark == 'LongMemEval' and enabled is None
    assert path.read_bytes() == raw
    return dict(identity)
def fixture_mapping(m, benchmark):
    assert m == mapping and benchmark == 'LongMemEval' and '_accepted_manifest_sha256' not in m

with mock.patch.object(ingest, 'verify_source_bytes', side_effect=fixture_bytes), \
     mock.patch.object(ingest, '_check_accepted_mapping', side_effect=fixture_mapping):
    ingested = ingest.ingest_longmemeval(path, copy.deepcopy(mapping))

calls = []
original = pipeline.score_archive
def observed(*args, **kwargs):
    result = original(*args, **kwargs)
    calls.append(dict(ordinal=args[4], question_ids=list(args[3]), diagnostics=copy.deepcopy(result[1])))
    return result
with mock.patch.object(pipeline, 'score_archive', side_effect=observed):
    prepared = pipeline.assemble_in_memory(ingested, dict.fromkeys(ids, float(3 / 110)))
envelope = bridge.prepare_synthetic_envelope(ingested, prepared, raw)
mismatches = []
for diag in envelope['diagnostics']:
    actual = next(x for x in calls if x['ordinal'] == diag['archive_ordinal'])
    if diag['question_ids'] != actual['question_ids']:
        mismatches.append(dict(archive_ordinal=diag['archive_ordinal'],
                               actual_preparation_question_ids=actual['question_ids'],
                               persisted_envelope_question_ids=diag['question_ids']))
report = dict(candidate='24d3351f068f6982148c14a9e3338c29a2769449',
              scope='Generated LME-shaped bytes only. Source/mapping checks substituted solely for exact generated fixture. Unchanged ingestion, representation, full controls, scoring and envelope builder. No bootstrap, production writer, finalizer or suite rerun.',
              cohort_order=ingested['cohort_ids'],
              true_assembly_order=[dict(ordinal=x['ordinal'], question_ids=x['question_ids']) for x in calls],
              envelope_accepted=True, record_count=len(prepared['records']),
              envelope_binding_sha256=envelope['binding_sha256'],
              mismatches=mismatches, reproduced=len(mismatches) == 2, data_events=events)
(AUDIT / 'LME_BINDING_REPRO.json').write_text(json.dumps(report, indent=2) + '\n', encoding='utf-8', newline='\n')
print(json.dumps(report))
assert report['reproduced'], 'Static finding not reproduced'
