"""Focused SYNTHETIC ONLY delivery tests; all artifacts stay under this owned clone.

No production authorization, accepted mapping stamps, corpus scans or frozen outcomes.
The source-binding mock below applies only to bytes generated by this test. Ingestion,
representation, scoring, aggregation and 10,000-replicate bootstrap run unchanged.
Inherited test assertions are not edited or relabeled as new independent acceptance.
"""
from __future__ import annotations

import copy
import hashlib
import json
import tempfile
import traceback
import unittest
from pathlib import Path
from unittest import mock

import numpy as np

import corpus_ingest_g3 as ingest
import integration_g3 as bridge
import membership_runner_g3 as runner
import pipeline_g3 as pipeline

HERE = Path(__file__).resolve().parent
CANARY = "SYNTHETIC_PRIVATE_CANARY_857"


def rebind(value, field="binding_sha256"):
    value[field] = bridge._digest({k: v for k, v in value.items() if k != field})


def surface(exc):
    parts, pending, seen = [], [exc], set()
    while pending:
        node = pending.pop()
        if id(node) in seen:
            continue
        seen.add(id(node))
        parts.extend((str(node), repr(node), "".join(traceback.format_exception(node))))
        pending.extend(x for x in (node.__cause__, node.__context__) if x is not None)
    return "\n".join(parts)


class DeliveryIntegration(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.tmp = tempfile.TemporaryDirectory(prefix="delivery_integration_", dir=HERE)
        cls.root = Path(cls.tmp.name)
        n = 110
        # All generated units are gold, so the independent native anchor is exactly 3/n.
        messages = [{"dia_id": f"D1:{j}", "speaker": "Fixture",
                     "text": f"synthetic archive token{j} topic{j % 13} item{j * 17} detail{j % 7}"}
                    for j in range(n)]
        evidence = [x["dia_id"] for x in messages]
        raw = json.dumps([{"conversation": {"session_1": messages}, "qa": [
            {"question": "synthetic topic3 item34 query", "evidence": evidence},
            {"question": "synthetic topic8 item51 query", "evidence": evidence}]}]).encode()
        cls.source_bytes = raw
        cls.path = cls.root / "synthetic_fixture.json"
        cls.path.write_bytes(raw)
        sha = hashlib.sha256(raw).hexdigest()
        cls.mapping = {"provenance": bridge.SYNTHETIC, "source_id": "synthetic_fixture",
            "source_sha256": sha, "benchmark": runner.LOCOMO, "n_questions": 2,
            "expected_cluster_ids": ["locomo_conv_0"],
            "expected_question_to_cluster": {"locomo_0_qa0": "locomo_conv_0", "locomo_0_qa1": "locomo_conv_0"}}
        cls.identity = {"source_file": cls.path.name, "source_sha256": sha, "source_bytes": len(raw)}

        def fixture_bytes(path, benchmark, *, enabled=None):
            assert Path(path) == cls.path and benchmark == runner.LOCOMO and enabled is None
            assert Path(path).read_bytes() == raw
            return dict(cls.identity)

        def fixture_mapping(mapping, benchmark):
            assert mapping == cls.mapping and benchmark == runner.LOCOMO
            assert "_accepted_manifest_sha256" not in mapping

        with mock.patch.object(ingest, "verify_source_bytes", side_effect=fixture_bytes), \
             mock.patch.object(ingest, "_check_accepted_mapping", side_effect=fixture_mapping), \
             mock.patch.object(runner.core, "require_real_data_authorization", side_effect=AssertionError("auth must not be called")):
            cls.ingested = ingest.ingest_locomo(cls.path, copy.deepcopy(cls.mapping))
        cls.prepared = pipeline.assemble_in_memory(cls.ingested, {q: float(3 / n) for q in cls.ingested["cohort_ids"]})
        cls.envelope = bridge.prepare_synthetic_envelope(cls.ingested, cls.prepared, raw)
        cls.result = bridge.compute_synthetic_result(cls.envelope)

    @classmethod
    def tearDownClass(cls):
        cls.tmp.cleanup()

    def refusal(self, call, code=None):
        with self.assertRaises(bridge.IntegrationError) as got:
            call()
        if code is not None:
            self.assertEqual(str(got.exception), code)
        self.assertNotIn(CANARY, surface(got.exception))
        self.assertIsNone(got.exception.__context__)
        self.assertIsNone(got.exception.__cause__)

    def test_real_fixture_ingress_assemble_bootstrap_output(self):
        self.assertEqual(len(self.prepared["records"]), 120)
        self.assertEqual(self.result["provenance"], bridge.SYNTHETIC)
        self.assertEqual(self.result["bootstrap_configuration"]["replicates"], 10000)
        self.assertEqual(self.result["bootstrap_configuration"]["seed"], 52001107)
        self.assertEqual(self.result["estimates"]["n_question_slots"], 2)
        self.assertEqual(self.result["preparation"]["source_identity"]["source_sha256"], hashlib.sha256(self.source_bytes).hexdigest())
        self.assertEqual(self.result["preparation"]["code_hashes"], bridge._code_hashes())
        self.assertNotIn("_accepted_manifest_sha256", json.dumps(self.result))
        self.assertNotIn("frozen_before_any_result", json.dumps(self.result))
        out = self.root / "result.json"
        bridge.write_synthetic_result(out, self.result)
        self.assertEqual(json.loads(out.read_bytes()), self.result)

    def test_shared_cluster_delegation_and_nonzero_point_estimates(self):
        e = copy.deepcopy(self.envelope)
        scores = {"NATIVE": .2, "SCALED_NATIVE": .2, "B32_FRESH": .6,
                  "RANDOM32_FRESH": .2, "SCALED_B32": .4, "SCALED_RANDOM32": .3}
        for row in e["records"]:
            row["fractional_R3"] = scores[row["arm"]]
        rebind(e)
        r = bridge.compute_synthetic_result(e, scheme="cluster")
        self.assertEqual(r["bootstrap_configuration"]["seed"], 52001207)
        self.assertEqual(r["uncertainty"]["replicates"], 10000)
        for key, expected in zip(bridge.SCALARS, (40., 10., -30.)):
            self.assertAlmostEqual(r["estimates"][key], expected)
            self.assertAlmostEqual(r["uncertainty"]["intervals"][key]["lo"], expected)
            self.assertAlmostEqual(r["uncertainty"]["intervals"][key]["hi"], expected)

    def test_malformed_records_refused_before_numerics(self):
        variants = []
        for field, values in {"question_id": [CANARY, 1], "rotation_seed": [60001.9, "60001", True],
                              "arm": [CANARY, None], "fractional_R3": [True, "bad", -1., 2., float("nan"), float("inf")]}.items():
            for value in values:
                e = copy.deepcopy(self.envelope)
                e["records"][0][field] = value
                variants.append(e)
        for kind in ("missing", "extra", "duplicate", "empty", "nondict"):
            e = copy.deepcopy(self.envelope)
            if kind == "missing":
                del e["records"][0]["fractional_R3"]
            elif kind == "extra":
                e["records"][0][CANARY] = CANARY
            elif kind == "duplicate":
                e["records"][1] = copy.deepcopy(e["records"][0])
            elif kind == "empty":
                e["records"] = []
            else:
                e["records"][0] = CANARY
            variants.append(e)
        with mock.patch.object(runner, "compute_synthetic_results") as compute:
            for e in variants:
                with self.subTest(record=e["records"][:1]):
                    self.refusal(lambda: bridge.compute_synthetic_result(e), "E-G3-I04")
            compute.assert_not_called()

    def test_diagnostics_mapping_and_provenance_negatives(self):
        mutations = [
            lambda e: e["diagnostics"][0].update({CANARY: CANARY}),
            lambda e: e["diagnostics"][0].update(degenerate_coords=True),
            lambda e: e["diagnostics"][0].update(archive_ordinal=0.0),
            lambda e: e["diagnostics"][0].update(flagged=1),
            lambda e: e["diagnostics"][0].update(cv_sigma_before=None),
            lambda e: e["diagnostics"].append(copy.deepcopy(e["diagnostics"][0])),
            lambda e: e["diagnostics"][0].update(question_ids=[]),
            lambda e: e["mapping"].update(_accepted_manifest_sha256=runner.accepted.ACCEPTED_MANIFESTS[runner.LOCOMO]["blob_sha256"]),
            lambda e: e["mapping"].update(n_questions=True),
            lambda e: e["mapping"].update(provenance="ACCEPTED"),
            lambda e: e["mapping"]["expected_question_to_cluster"].update(locomo_0_qa0="wrong"),
            lambda e: e["source_identity"].update(source_sha256="0" * 64),
            lambda e: e["source_identity"].update(source_bytes=True),
            lambda e: e["code_hashes"].update({"membership_scaling_core.py": "0" * 64}),
            lambda e: e.update(provenance="ACCEPTED", benchmark=CANARY),
        ]
        with mock.patch.object(runner, "compute_synthetic_results") as compute:
            for change in mutations:
                e = copy.deepcopy(self.envelope)
                change(e)
                rebind(e)  # Even a rebuilt public hash cannot bypass structural/semantic checks.
                self.refusal(lambda: bridge.compute_synthetic_result(e))
            compute.assert_not_called()

    def test_stale_binding_and_detached_inputs(self):
        e = bridge.prepare_synthetic_envelope(self.ingested, self.prepared, self.source_bytes)
        self.assertIsNot(e["mapping"], self.ingested["mapping"])
        self.assertIsNot(e["records"][0], self.prepared["records"][0])
        before = copy.deepcopy(e)
        r = bridge.compute_synthetic_result(e)
        self.assertEqual(e, before)
        e["records"][0]["fractional_R3"] = .99
        e["diagnostics"][0]["question_ids"].append(CANARY)
        self.assertEqual(r["preparation"], before)
        e = copy.deepcopy(self.envelope)
        e["records"][0]["fractional_R3"] = .99
        self.refusal(lambda: bridge.compute_synthetic_result(e), "E-G3-I11")
        r["preparation"]["code_hashes"]["pipeline_g3.py"] = "0" * 64
        self.assertEqual(bridge._code_hashes(), self.envelope["code_hashes"])

    def test_builder_refuses_source_swap_and_raw_diag_subclass(self):
        self.refusal(lambda: bridge.prepare_synthetic_envelope(self.ingested, self.prepared, b"wrong"), "E-G3-I10")
        class BadInt(int):
            def __repr__(self):
                raise RuntimeError(CANARY)
        p = copy.deepcopy(self.prepared)
        p["diagnostics"][0]["degenerate_coords"] = BadInt(1)
        self.refusal(lambda: bridge.prepare_synthetic_envelope(self.ingested, p, self.source_bytes), "E-G3-I01")

    def test_undefined_cv_has_explicit_json_null_status(self):
        p = copy.deepcopy(self.prepared)
        _, diag = runner.core.scale_matrix(np.zeros((110, 96)))
        p["diagnostics"] = [dict(archive_ordinal=0, **diag)]
        e = bridge.prepare_synthetic_envelope(self.ingested, p, self.source_bytes)
        r = bridge.compute_synthetic_result(e)
        out = self.root / "undefined.json"
        bridge.write_synthetic_result(out, r)
        decoded = json.loads(out.read_bytes(), parse_constant=lambda x: self.fail("nonstandard JSON constant"))
        d = decoded["preparation"]["diagnostics"][0]
        self.assertIsNone(d["cv_sigma_before"])
        self.assertEqual(d["cv_sigma_before_status"], "undefined_zero_mean")
        self.assertIsNone(d["cv_sigma_after"])

    def test_strict_output_negatives_before_open(self):
        mutations = [
            lambda r: r["estimates"].update({CANARY: CANARY}),
            lambda r: r["estimates"].update(n_question_slots=True),
            lambda r: r["estimates"].update(per_seed_G_pp=[0.]),
            lambda r: r["bootstrap_configuration"].update(replicates=1),
            lambda r: r["bootstrap_configuration"].update(seed=True),
            lambda r: r["uncertainty"]["intervals"]["G_bar_pp"].update(lo=1., hi=-1.),
            lambda r: r["uncertainty"]["intervals"]["G_bar_pp"].update(spans_zero="yes"),
            lambda r: r["uncertainty"].update(interpretation=CANARY),
        ]
        for mutate in mutations:
            r = copy.deepcopy(self.result)
            mutate(r)
            rebind(r, "result_sha256")
            target = self.root / "invalid-output.json"
            original = Path.open
            modes = []
            def read_only(path, mode="r", *args, **kwargs):
                modes.append(mode)
                return original(path, mode, *args, **kwargs)
            with mock.patch.object(Path, "open", new=read_only):
                self.refusal(lambda: bridge.write_synthetic_result(target, r))
            self.assertTrue(all("x" not in mode and "w" not in mode for mode in modes))
            self.assertFalse(target.exists())
        r = copy.deepcopy(self.result)
        r["estimates"]["G_bar_pp"] = float("nan")
        self.refusal(lambda: bridge.write_synthetic_result(self.root / "nan.json", r))
        self.assertFalse((self.root / "nan.json").exists())

    def test_exclusive_create_race_and_unchanged_sentinel(self):
        target = self.root / "existing.json"
        sentinel = b"unchanged sentinel bytes\x00\xff"
        target.write_bytes(sentinel)
        self.refusal(lambda: bridge.write_synthetic_result(target, self.result), "E-G3-I98")
        self.assertEqual(target.read_bytes(), sentinel)
        race = self.root / "race.json"
        original = Path.open
        def racing_open(path, mode="r", *args, **kwargs):
            if path == race and mode == "xb":
                with original(path, "xb") as stream:
                    stream.write(sentinel)
            return original(path, mode, *args, **kwargs)
        with mock.patch.object(Path, "open", new=racing_open):
            self.refusal(lambda: bridge.write_synthetic_result(race, self.result), "E-G3-I98")
        self.assertEqual(race.read_bytes(), sentinel)

    def test_library_and_path_error_surfaces(self):
        with mock.patch.object(runner, "compute_synthetic_results", side_effect=RuntimeError(CANARY)):
            self.refusal(lambda: bridge.compute_synthetic_result(self.envelope), "E-G3-I90")
        self.refusal(lambda: bridge.write_synthetic_result(self.root / CANARY / "missing.json", self.result), "E-G3-I90")

    def test_seed_single_snapshot(self):
        cfg = runner.accepted_bootstrap_for(runner.LOCOMO, "question")
        record = {"benchmark": runner.LOCOMO, "scheme": "question", "bootstrap_seed": cfg["seed"],
                  "replicates": cfg["replicates"]}
        raw = json.dumps(record).encode()
        with mock.patch.object(Path, "exists", return_value=True), \
             mock.patch.object(Path, "read_bytes", side_effect=[raw, b"changed second read"]) as reads, \
             mock.patch.object(Path, "read_text", side_effect=AssertionError("second reader")):
            got = runner.read_bootstrap_seed(self.root / "in_memory_seed.json", runner.LOCOMO, "question")
        self.assertEqual(reads.call_count, 1)
        self.assertEqual(got["sha256"], hashlib.sha256(raw).hexdigest())
        self.assertEqual(got["bootstrap_seed"], cfg["seed"])

    def test_production_entry_names_refuse(self):
        for fn in (bridge.compute_accepted_result, bridge.write_accepted_result, bridge.run_on_real_corpus):
            self.refusal(lambda: fn(enabled=True), "E-G3-I99")
        self.assertFalse(runner.core.REAL_DATA_EXECUTION_ENABLED)


if __name__ == "__main__":
    unittest.main(verbosity=2)
